displayName=SkillRaceCreator
author=Oyama
support=https://github.com/ItMeansBigMountain/SkillRaceCreator
description=SkillRaceCreator RuneLite plugin.
tags=skillracecreator,runelite,osrs
plugins=com.itmeansbigmountain.skillracecreator.SkillRaceCreatorPlugin
